### ISSUE TITLE
Relate Work Stool - Not working

### ISSUE THREAD

**Issue by WilliamsHeidi** [Allsteel/sku#15]
Can you tell me if the Relate Work Stool has been set up in the sku server?

I tried this url and didn't get anything back.
http://skuserver.azurewebsites.net/page/rls-mhpfc.1.l.cbklkm01.pnl04/1000/all

**Comment by tucaz** [comment]
1 is not a valid cylinder in the work stool. 4 is the only available option so the correct SKU is 

RLS-MHPFC.4.0.L.CBKLKM01.PNL04

http://skuserver.azurewebsites.net/page/RLS-MHPFC.4.0.L.CBKLKM01.PNL04/1000/all
