### ISSUE TITLE
Ready for sku server - Rise

### ISSUE THREAD

**Issue by WilliamsHeidi** [Allsteel/sku#24]
Rise is ready to be configured on the sku server.

**Comment by tucaz** [comment]
It is published. This item has two special accessories that should be included in the SKU after the main SKU.

2 Tier - http://qa-skuapp.azurewebsites.net/page/S922S2.FSC.WTH02/1000/all
2 Tier with black power outlet - http://qa-skuapp.azurewebsites.net/page/S922S2P.FSC.WTH02,S922PC.BLK/1000/all
2 Tier with PR6 tray and white power outlet - http://qa-skuapp.azurewebsites.net/page/S922S2P.FSC.WTH02,S922T.PR6,S922PC.BLK/1000/all

If a model has both tray and power outlet, the tray should be the first accessory in the SKU
