### ISSUE TITLE
Clarity - .PQ8 option

### ISSUE THREAD

**Issue by WilliamsHeidi** [Allsteel/sku#26]
I am receiving the following message from Nicole... Is this a sku server configuration issue or Farm CP?

http://qa-skuapp.azurewebsites.net/page/c4amfc.cm25.pq8.g.pal.5.gld/1000/all

The frame color shows .pq8 but looks like polished aluminum.
The base shows polished in the listing but looks like Titanium plastic.

**Comment by tucaz** [comment]
The base has been fixed (only PAL was wrong). 

The frame color (PQ8) looks white-ish alright to me. If it's not looking right then we have to ask for Farm CP to adjust it.
