### ISSUE TITLE
Tolleson - Casters

### ISSUE THREAD

**Issue by WilliamsHeidi** [Allsteel/sku#28]
T-SLAP model is not allowing for casters.

http://qa-skuapp.azurewebsites.net/page/t-slapfc.2.pr1.p71.ade20/1000/all

T-KLAO model is not allowing for casters.

http://qa-skuapp.azurewebsites.net/page/t-klapfc.3.p71.p71.man012/1000/all

**Comment by tucaz** [comment]
@WilliamsHeidi the pricer states on **page 112** under **1st option** that *"Casters not available on armless versions"* so Farm CP didn't include them in the vignettes.

If you go with a version that has arms the casters will be there 

http://qa-skuapp.azurewebsites.net/page/t-slopfc.2.pr1.p71.ade20/1000/all
